name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Risolve il warning relativo alla deprecazione di Node.js 20
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # Usa una versione stabile (3.11 o 3.12) per evitare problemi di incompatibilità
        # pacchetti o Pyinstaller in ambiente Windows
        python-version: '3.11' 
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build application with PyInstaller
      run: |
        # Usare "python -m PyInstaller" su Windows è più sicuro
        python -m PyInstaller Palestra3000.spec
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Palestra3000-executable
        path: dist/